---
name: dist

on:
  pull_request:
  push:
    branches:
    - '*'
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Set ccache variant
      shell: bash
      id: ccache
      run: |
        #if [[ "${{ runner.os }}" == "Windows" ]]; then
        #  echo "VARIANT=sccache" >> $GITHUB_OUTPUT
        #  echo "RPYBUILD_CC_LAUNCHER=sccache" >> $GITHUB_ENV
        #else
          echo "VARIANT=ccache" >> $GITHUB_OUTPUT
          echo "RPYBUILD_CC_LAUNCHER=ccache" >> $GITHUB_ENV
        #fi

    - name: Setup ccache
      # uses: hendrikmuhs/ccache-action@v1.2.11
      uses: robotpy/ccache-action@fork
      with:
          key: ubuntu-3.13
          variant: ${{ steps.ccache.outputs.variant }}

    - uses: robotpy/build-actions/install-robotpy-build@v2025
    - uses: robotpy/build-actions/install-build-deps@v2025
    - uses: robotpy/build-actions/build-wheel@v2025
      with:
        osx_target: ${{ inputs.osx_target }}

    - uses: robotpy/build-actions/test-native-wheel@v2025

    - uses: robotpy/build-actions/validate-sphinx@v2025
      if: |
        inputs.enable_sphinx_check && inputs.enable_rtd &&
        matrix.python_version == '3.11' && runner.os == 'Linux' &&
        github.event_name == 'pull_request'

    - uses: actions/upload-artifact@v4
      with:
        name: "pypi-${{ runner.os }}-3.13"
        path: dist
